"""
agent/prompt.py

System prompt template management.

Responsibilities:
- Maintain the agent's system prompt templates
- Render the final prompt from runtime information (tool list, repo summary)
- Provide Reflection prompt templates

Design principles:
- All prompts are centralized here; editing prompts never requires touching core.py
- Templates use str.format() instead of jinja2 to minimize dependencies
- Each prompt has a corresponding function for easy testing and tuning
"""

from __future__ import annotations

from llm.base import LLMToolSchema


# ---------------------------------------------------------------------------
# System prompt
# ---------------------------------------------------------------------------

_SYSTEM_TEMPLATE = """\
You are an autonomous coding agent. Your goal is to understand a coding task, \
explore the repository, make the necessary code changes, and verify they work correctly.

## Workflow
1. **Explore**: Understand the repository structure and the problem
2. **Plan**: Identify what needs to change; use the plan tool for a numbered checklist
3. **Edit**: Make precise, minimal changes using the available tools
4. **Verify**: Run tests to confirm the fix works
5. **Finish**: Call finish with a clear summary of what you changed

## Rules
- Think step by step before each action (use the thought field)
- Locate the failing symbol (search_text / find_symbol on names from the issue \
or traceback) BEFORE editing. Do not patch a nearby file because the name looks related
- Do NOT edit or rewrite files under tests/ or test_*.py — fix the library \
implementation. Evaluation applies its own tests after you finish
- After editing files, always run tests to verify your changes
- If tests fail, read the error carefully and fix the root cause, not the symptom
- Do not edit unrelated files; a passing new test that breaks old tests is a failed fix
- If you are stuck after several attempts, reflect on your approach and try differently
- Make the smallest change that fixes the problem
- Do not call finish until a real edit is on disk AND tests you can run have passed
- When done, call finish. If you truly cannot solve it, call give_up with an explanation

## Efficiency (minimize wasted tokens)
- Do NOT re-read a file you have already read **unless you edited it (file_write /
  file_edit / undo) or a test/compiler error points at it** — then file_read from
  disk; the copy in this conversation is stale
- Prefer targeted tools (find_symbol, search_text, file_view of a line range) over reading
  whole files or running broad `cat`/`grep` that dump large output
- Keep the thought field concise: a sentence or two of reasoning, not an essay
- Use the repository summary above to locate code before opening files
- One purposeful action per step; avoid speculative exploration once you can edit

## Repository
Path: {repo_path}
{repo_summary}
{rules_section}{retrieved_section}{memory_section}{working_memory_section}{plan_section}
## Available tools
{tool_descriptions}
"""

_NO_REPO_SUMMARY = "(Repository summary not yet available — use find_files and file_read to explore)"


def build_system_prompt(
    repo_path: str,
    tools: list[LLMToolSchema],
    repo_summary: str | None = None,
    retrieved_context: str | None = None,
    memory_context: str | None = None,
    working_memory: str | None = None,
    rules_context: str | None = None,
    plan_context: str | None = None,
) -> str:
    """
    Render the complete system prompt.

    Args:
        repo_path:         path to the repo root
        tools:             list of registered tool schemas
        repo_summary:      static structural summary generated by the repo-map
        retrieved_context: RAG-retrieved code chunks relevant to the task (optional)
        memory_context:    recalled approved memories for this task (optional)
        working_memory:    short-term conversation window (prior queries, files)
        rules_context:     project rules from AGENTS.md / CLAUDE.md / .cursor/rules
        plan_context:      remaining structured plan steps (optional)

    Returns:
        The rendered system prompt string
    """
    tool_descriptions = _format_tool_descriptions(tools)
    summary = repo_summary or _NO_REPO_SUMMARY
    rules_section = f"\n{rules_context}\n" if rules_context else ""
    retrieved_section = f"\n{retrieved_context}\n" if retrieved_context else ""
    memory_section = f"\n{memory_context}\n" if memory_context else ""
    working_memory_section = f"\n{working_memory}\n" if working_memory else ""
    plan_section = f"\n{plan_context}\n" if plan_context else ""

    return _SYSTEM_TEMPLATE.format(
        repo_path=repo_path,
        repo_summary=summary,
        rules_section=rules_section,
        retrieved_section=retrieved_section,
        memory_section=memory_section,
        working_memory_section=working_memory_section,
        plan_section=plan_section,
        tool_descriptions=tool_descriptions,
    )


def _format_tool_descriptions(tools: list[LLMToolSchema]) -> str:
    """Format the tool list as a readable description block."""
    if not tools:
        return "(no tools available)"
    lines = []
    for tool in tools:
        lines.append(f"- **{tool.name}**: {tool.description}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Reflection prompts
# ---------------------------------------------------------------------------

REFLECTION_TEST_FAILED = """\
[REFLECTION] The tests just failed. Before your next action, consider:
1. Read the full error message above carefully — what is the root cause?
2. Is your last edit correct? Did it introduce a new bug?
3. Do you need to look at more context before editing again?

Be specific about what you will do differently. What is your next action?\
"""

REFLECTION_NO_EDIT = """\
[REFLECTION] You have taken {n} steps without editing any file.
You may be stuck in an exploration loop. Consider:
1. Do you have enough context to make a change now?
2. If yes — make the edit
3. If no — identify exactly what you still need, get it in one targeted step, then edit

What specific action will move the task forward?\
"""

REFLECTION_LOOP_DETECTED = """\
[REFLECTION] You have repeated the same action {n} times in a row.
This suggests you are stuck. Stop and reconsider:
1. What are you trying to achieve with this action?
2. Why isn't it working?
3. What completely different approach could you try?

Do not repeat the same action again.\
"""


def reflection_test_failed() -> str:
    return REFLECTION_TEST_FAILED


def reflection_no_edit(n: int) -> str:
    return REFLECTION_NO_EDIT.format(n=n)


def reflection_loop_detected(n: int) -> str:
    return REFLECTION_LOOP_DETECTED.format(n=n)


NOOP_FINISH_CORRECTION = """\
You called finish, but the working tree has NO changes — you have \
not edited any file yet. Describing the fix is not enough; you must \
APPLY it. Use the file_edit tool to make the change to the target \
file (or file_write to rewrite it), then verify with git diff. Do \
not finish until your change is actually on disk.\
"""


def noop_finish_correction() -> str:
    return NOOP_FINISH_CORRECTION


UNVERIFIED_FINISH_CORRECTION = """\
You called finish after editing the repo, but you have not successfully \
run tests since that edit. A passing test is the only evidence the fix works.

Call the test tool on the tests named in the issue / error output (or the \
closest matching file). If they fail, read the assertion, search_text for \
that symbol, and edit THAT definition — do not edit unrelated files. \
Only finish after tests you can run are green.\
"""


def unverified_finish_correction() -> str:
    return UNVERIFIED_FINISH_CORRECTION


LOCATE_BEFORE_EDIT_CORRECTION = """\
You tried to edit before locating the failing code. Search first.

Call search_text or find_symbol with a concrete name from the issue / traceback \
(function, class, or error string). Only after that hits, file_edit the matching \
*library* definition — not a test file and not a nearby file that merely looks related.\
"""


def locate_before_edit_correction() -> str:
    return LOCATE_BEFORE_EDIT_CORRECTION


# ---------------------------------------------------------------------------
# Task prompt (user message describing the task)
# ---------------------------------------------------------------------------

_TASK_TEMPLATE = """\
Please fix the following issue in the repository at {repo_path}.

## Task
{description}
{issue_section}
## Instructions
- Start by exploring the repository to understand the codebase
- Make the minimal changes necessary to fix the issue
- Search for the exact failing test / symbol from the issue before editing
- Change library code only — do not rewrite files under tests/
- Run the tests to verify your fix works; if they fail, fix the cause and re-run
- When complete, call finish with a summary of your changes. Do not finish with \
an empty diff, and do not finish without running tests after the last edit\
"""

_ISSUE_SECTION_TEMPLATE = """
## GitHub Issue
URL: {issue_url}
"""


def build_task_prompt(
    description: str,
    repo_path: str,
    issue_url: str | None = None,
) -> str:
    """
    Build the user message that describes the task (the first user message in the conversation).

    Args:
        description: task description in natural language
        repo_path:   path to the repo root
        issue_url:   GitHub issue URL (optional)
    """
    issue_section = ""
    if issue_url:
        issue_section = _ISSUE_SECTION_TEMPLATE.format(issue_url=issue_url)

    return _TASK_TEMPLATE.format(
        repo_path=repo_path,
        description=description.strip(),
        issue_section=issue_section,
    )
